apiVersion: flagger.app/v1beta1
kind: Canary
metadata:
  name: nginx-dev
  namespace: dev
spec:
  targetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: dev-nginx
  service:
    port: 80
  ingressRef:
    apiVersion: networking.k8s.io/v1
    kind: Ingress
    name: dev-nginx
  analysis:
    interval: 1m
    threshold: 10
    maxWeight: 50
    stepWeight: 5
    metrics:
      - name: request-success-rate
        threshold: 99
        interval: 1m
      - name: request-duration
        threshold: 500
        interval: 30s

